
// This file has been generated by the GUI designer. Do not modify.
namespace ToyLanguage_NET
{
	public partial class InputProgramWindow
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView textview;
		
		private global::Gtk.Button btnNew;
		
		private global::Gtk.Button btnBack;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ToyLanguage_NET.InputProgramWindow
			this.Name = "ToyLanguage_NET.InputProgramWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("InputProgramWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ToyLanguage_NET.InputProgramWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview = new global::Gtk.TextView ();
			this.textview.CanFocus = true;
			this.textview.Name = "textview";
			this.GtkScrolledWindow.Add (this.textview);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.btnNew = new global::Gtk.Button ();
			this.btnNew.CanFocus = true;
			this.btnNew.Name = "btnNew";
			this.btnNew.UseUnderline = true;
			this.btnNew.Label = global::Mono.Unix.Catalog.GetString ("New");
			this.vbox2.Add (this.btnNew);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.btnNew]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.btnBack = new global::Gtk.Button ();
			this.btnBack.CanFocus = true;
			this.btnBack.Name = "btnBack";
			this.btnBack.UseUnderline = true;
			this.btnBack.Label = global::Mono.Unix.Catalog.GetString ("Back");
			this.vbox2.Add (this.btnBack);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.btnBack]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.btnNew.Clicked += new global::System.EventHandler (this.newTouched);
			this.btnBack.Clicked += new global::System.EventHandler (this.backTouched);
		}
	}
}
