
// This file has been generated by the GUI designer. Do not modify.
namespace ToyLanguage_NET
{
	public partial class MyDialogBox
	{
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.Label mainLabel;
		
		private global::Gtk.ComboBox comboBox;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ToyLanguage_NET.MyDialogBox
			this.Name = "ToyLanguage_NET.MyDialogBox";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child ToyLanguage_NET.MyDialogBox.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.mainLabel = new global::Gtk.Label ();
			this.mainLabel.Name = "mainLabel";
			this.mainLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.vbox6.Add (this.mainLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.mainLabel]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.comboBox = global::Gtk.ComboBox.NewText ();
			this.comboBox.Name = "comboBox";
			this.vbox6.Add (this.comboBox);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.comboBox]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			w1.Add (this.vbox6);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox6]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Internal child ToyLanguage_NET.MyDialogBox.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "dialog1_ActionArea";
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.buttonOk]));
			w6.Expand = false;
			w6.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.comboBox.Changed += new global::System.EventHandler (this.changedValue);
			this.buttonOk.Clicked += new global::System.EventHandler (this.okButtonTouched);
		}
	}
}
