
// This file has been generated by the GUI designer. Do not modify.
namespace ToyLanguage_NET
{
	public partial class OneStepWindow
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView textView;
		
		private global::Gtk.Button btnOneStep;
		
		private global::Gtk.Button btnBack;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ToyLanguage_NET.OneStepWindow
			this.Name = "ToyLanguage_NET.OneStepWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("OneStepWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ToyLanguage_NET.OneStepWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textView = new global::Gtk.TextView ();
			this.textView.CanFocus = true;
			this.textView.Name = "textView";
			this.GtkScrolledWindow.Add (this.textView);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.btnOneStep = new global::Gtk.Button ();
			this.btnOneStep.CanFocus = true;
			this.btnOneStep.Events = ((global::Gdk.EventMask)(256));
			this.btnOneStep.Name = "btnOneStep";
			this.btnOneStep.UseUnderline = true;
			this.btnOneStep.Label = global::Mono.Unix.Catalog.GetString ("One Step");
			this.vbox1.Add (this.btnOneStep);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.btnOneStep]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.btnBack = new global::Gtk.Button ();
			this.btnBack.CanFocus = true;
			this.btnBack.Events = ((global::Gdk.EventMask)(256));
			this.btnBack.Name = "btnBack";
			this.btnBack.UseUnderline = true;
			this.btnBack.Label = global::Mono.Unix.Catalog.GetString ("Back");
			this.vbox1.Add (this.btnBack);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.btnBack]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.btnOneStep.Clicked += new global::System.EventHandler (this.oneStepTouched);
			this.btnBack.Clicked += new global::System.EventHandler (this.backTouched);
		}
	}
}
